# Generated by Django 6.0.3 on 2026-04-14 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_date_of_birth_useractiontoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractiontoken',
            name='date_of_birth',
        ),
        migrations.CreateModel(
            name='UserActionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=10)),
                ('action_type', models.CharField(choices=[('authorization', 'Authorization')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
