# Generated by Django 6.0.3 on 2026-04-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_useractiontoken_date_of_birth_useractioncode'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractiontoken',
            name='value',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
