# Generated by Django 6.0.3 on 2026-04-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_useractiontoken_value_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractiontoken',
            name='action_type',
            field=models.CharField(choices=[('activation', 'Activation'), ('password_reset', 'Password Reset'), ('email_change', 'E-mail change')], max_length=20),
        ),
    ]
