# Generated by Django 6.0.3 on 2026-04-23 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_useractiontoken_action_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='currency',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
