# Generated by Django 6.0.3 on 2026-05-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_currency_delete_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_system_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='memo_id',
            field=models.PositiveIntegerField(db_index=True, null=True, unique=True),
        ),
    ]
