# Generated by Django 6.0.3 on 2026-04-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiatCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('symbol', models.CharField(blank=True, max_length=5, null=True)),
                ('conversion_rate', models.DecimalField(decimal_places=8, default=1.0, max_digits=18, verbose_name='Coversion rate (USD to ...)')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fiat Currency',
                'verbose_name_plural': 'Fiat Currencies',
            },
        ),
    ]
