# Generated by Django 6.0.3 on 2026-04-30 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('native', 'Native'), ('contract', 'Contract')], default='contract', max_length=20)),
                ('address', models.CharField(blank=True, help_text='Contract address (empty for native)', max_length=255, null=True)),
                ('precision', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CryptoCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(db_index=True, max_length=15, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='currencies/coins/')),
                ('coingecko_id', models.CharField(max_length=15)),
                ('website_urls', models.TextField(blank=True, help_text='Website urls (divided by ;)', null=True)),
                ('description', models.TextField()),
                ('issue_date', models.DateField()),
                ('static_extra_data', models.JSONField(default=dict)),
                ('price', models.DecimalField(decimal_places=18, default=0, max_digits=36)),
                ('change_24h', models.FloatField(default=0)),
                ('market_cap', models.DecimalField(decimal_places=2, default=0, max_digits=36)),
                ('trading_vol_24h', models.DecimalField(decimal_places=2, default=0, max_digits=36)),
                ('extra_data', models.JSONField(default=dict)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('origin_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_origin_for', to='currencies.blockchainasset')),
                ('parent_coin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='currencies.cryptocoin', verbose_name='Parent coin (if wrapped)')),
            ],
        ),
        migrations.AddField(
            model_name='blockchainasset',
            name='coin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='currencies.cryptocoin'),
        ),
        migrations.CreateModel(
            name='CryptoNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('ton', 'TON')], max_length=15, unique=True)),
                ('explorer_url', models.CharField(blank=True, help_text='Exporer url with format {address}', max_length=255, null=True)),
                ('native_asset', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_primary_for', to='currencies.blockchainasset')),
            ],
        ),
        migrations.AddField(
            model_name='blockchainasset',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='currencies.cryptonetwork'),
        ),
        migrations.AlterUniqueTogether(
            name='blockchainasset',
            unique_together={('coin', 'network')},
        ),
    ]
