# Generated by Django 6.0.3 on 2026-04-30 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_blockchainasset_cryptocoin_blockchainasset_coin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocoin',
            name='coingecko_id',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='cryptonetwork',
            name='native_asset',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_primary_for', to='currencies.blockchainasset'),
        ),
    ]
