# Generated by Django 6.0.3 on 2026-04-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_alter_cryptocoin_coingecko_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='cryptocoin',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='cryptocoin',
            name='static_extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cryptocoin',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='currencies.cryptocategory'),
        ),
    ]
