# Generated by Django 6.0.3 on 2026-05-01 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0004_cryptocategory_alter_cryptocoin_extra_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptonetwork',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='currencies/network/'),
        ),
    ]
