# Generated by Django 6.0.3 on 2026-05-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0005_cryptonetwork_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocoin',
            name='slug',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
