# Generated by Django 6.0.3 on 2026-05-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0006_cryptocoin_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocoin',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
