# Generated by Django 6.0.3 on 2026-05-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0007_alter_cryptocoin_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainasset',
            name='service_fee_fixed_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cryptonetwork',
            name='service_fee_fixed_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cryptonetwork',
            name='explorer_url',
            field=models.CharField(blank=True, help_text='Exporer url with format {tx_hash}', max_length=255, null=True),
        ),
    ]
